# .github/workflows/test-and-release.yaml

name: Test and Release
on: [push]

jobs:
  test-and-release:
    name: Run tests and release
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.17
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Build dist
      run: npm run dist
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release